### ISSUE TITLE
clarify settings for unsupervised uot

### ISSUE THREAD

**Issue by mickeymickeymonkey** [yukiar/OTAlign#3]
hello! your work is awesome, thank you for the repo! I have questions about the right settings to use, can you please help?

for unsupervsed OT case:
- What is 'chimera' setting in the arguments? I cannot tell from the description in help text under argparse. in paper I also cannot find this chimera/bertscore setting. from code in  unsupervised_alignment.py, I see this is added to tau term (control for penalisation of mass deviations, is that right?) and it is hyperparam that is searched for 

about example code for unsupervised case in README:
- it says layer=3, but your paper says layer=10. what should I look at for deciding which layer to use?
 
thank you for your help!

**Comment by mickeymickeymonkey** [comment]
also, I am unsure of the difference between 'uot' and 'uot-mm' setting for ot_type. which rows of Table 6 of the paper do they match with?

**Comment by yukiar** [comment]
Please ignore these, which were used for internal experiments only.
